### PR TITLE
Prevent ember-cli watcher being assigned to node_modules

### LINKED ISSUE #61: Watchers assigned to every included node path
One of the projects I work on started hitting the OSX file descriptor limit.  I was able to reduce down much of the issue with `DEBUG=broccoli-sane-watcher ember s` and saw most addons that use funnel/mergeTree to pull in node deps will get a watcher assigned to them.

```js
var app = new EmberApp(defaults, {
  nodeModulesToVendor: [
    'node_modules/moment/'
  ]
});
```

```
broccoli-sane-watcher [TreeMerger (vendor)#734 -> BroccoliMergeTrees#759 -> node_modules/moment/#760] addWatchDir: node_modules/moment/ +8ms
```

I'll submit a PR to use `UnwatchedDir` to prevent them from having a watcher assigned - since it's rare that you would ever want to watch node deps as they're not changing (usually) after app boot.  Each watcher can take somewhere between 10ms-150ms and when there are 180 watchers setup - this quickly adds up.  So file descriptor limit aside, there are positive perf improvements with this change.

### PR DESCRIPTION
**Pull request by jasonmit**
Fixes #61

Also went ahead and removed the addon folder since the presence of it causes warnings in the parent project:

```
DEPRECATION: Addon files were detected in `/Users/jasonmit/projects/foo/node_modules/ember-cli-node-modules-to-vendor/addon`, but no JavaScript preprocessors were found for `ember-cli-node-modules-to-vendor`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-cli-node-modules-to-vendor`'s `package.json`.
```

### CODE REVIEW

**Comment by kellyselden** [comment]
Mind removing the yarn file, then we will get this merged.

**Comment by jasonmit** [comment]
@kellyselden done

**Comment by kellyselden** [comment]
Thank you!

**Comment by kellyselden** [comment]
Released in v0.2.2

**Comment by stefanpenner** [comment]
I would prefer sane be fixed, then going around patching all libraries to not-watch.

**Pull request merged**
